### ISSUE TITLE
Rework tutorial notebook

### ISSUE THREAD

**Issue by sloede** [klimakoffer/Klimakoffer.jl#11]
Also, please make sure that the tutorial notebook still works (probably in a separate PR). Right now, the notebook assumes a relative path wrt to where Klimakoffer is located, which doesn't really fit anymore.

_Originally posted by @sloede in https://github.com/klimakoffer/Klimakoffer.jl/pull/10#r735714549_

Optimally, the notebook should contain only something like "Make sure the notebook is copied to the root directory of Klimakoffer.jl, then load Klimakoffer.jl with `using Klimakoffer`" or something similar.

**Comment by jmark** [comment]
Rework done.

https://nbviewer.org/urls/gist.githubusercontent.com/jmark/bd7d5b8ba88d1915e966c417b61d0637/raw/klimakoffer.ipynb
