### ISSUE TITLE
Decide on the use of Unicode characters

### ISSUE THREAD

**Issue by sloede** [klimakoffer/Klimakoffer.jl#8]
As discussed https://github.com/klimakoffer/Klimakoffer.jl/pull/7/files#r714518978, we should decide whether we want to allow Unicode characters as code (in comments and docstrings it is definitely ok). There are arguments for and against it (see e.g. the Trixi.jl discussions), but the summary is that with Unicode it *can* be nicer to read, while without Unicode it is *usually* safer and less ambiguous.

Even if it is decided that we allow Unicode in the code, we should specifically decide whether redefining `π` is OK or not (see https://github.com/klimakoffer/Klimakoffer.jl/pull/7/files#r714595082).

**Comment by gregorgassner** [comment]
I recommend to follow the Trixi guidelines here, as we want to incorporate it also in trixi-framework.

Unicode is ok in comments, etc. 
But no Unicode in the actual programme...

If I remember correctly, this is also what we decided on when we started Klimakoffer.jl - I will discuss this tomorrow with all participants and we let democracy win :-) 

In any case, I would never re-use pi for something else, that is quite dangerous imo :-)

**Comment by sloede** [comment]
Please note that while I am generally in favor of all-ASCII characters for code, I have never worked with non-ASCII characters and thus have little experience. Who knows, maybe it is even better than we think? Since I see this as a good opportunity to try out new things, I would personally favor to keep the Greek (maybe only rename `π` to something like `π_`). We can always go back to non-ASCII if we think it is necessary.

As a third option (and somewhat of a compromise), we could stipulate that all *user-visible* code must be non-ASCII. That is, function argument names, function names, type names etc. should be all-ASCII, while Greek and other non-ASCII symbols are only used within a single function. Although after writing this I can already see that this might not scale well (at least not for function argument names), hmmmm.... :thinking:

Tough decision! Please keep me posted about what you conclude. I have a commit ready that discards all newly introduced non-ASCII symbols in case it is needed.

**Comment by ranocha** [comment]
I have no horses in this race but I definitely prefer using some common Unicode characters also in the code - `λ` is just faster/easier to parse than `lambda` when reading it and code is written to be *read*.

**Comment by sloede** [comment]
> I have no horses in this race

O RLY? You only want to use this as a coding style Trojan horse to get Unicode characters into Trixi! Very sneaky, Mr. Ranocha, very sneaky...

**Comment by ranocha** [comment]
Caught :sweat_smile:

**Comment by ranocha** [comment]
You should definitely program some Python to appreciate the possibility to write Unicode characters - having read thousands of variables named `lamda` or `lam` makes you wish you could just read `λ` (note that you can't write `lambda` in Python since that's a keyword).

**Comment by jmark** [comment]
How do you guys conveniently type unicode characters? Do I really have to learn all the unicode character codes? Or do you really copy paste the character from somewhere else into the code? Or are there features provided by IDEs?

**Comment by sloede** [comment]
Most editors allow them to type them as Latex-style commands, e.g., `\lambda + <tab> + <tab>` (including auto completion). For vi, there's e.g. the `julia-vim` plugin that enables this.

In the Julia REPL, this works as well.

**Comment by jmark** [comment]
I also have the complete opposite opinion about readability to what @ranocha thinks.

**Comment by ranocha** [comment]
Well, I think there is a reason we see `λ` in equations in a paper and not `lambda` but YMMV. I'll leave this discussion unless you ping me explicitly

**Comment by sloede** [comment]
> I'll leave this discussion unless you ping me explicitly

Argh, I was too late :disappointed:

**Comment by jmark** [comment]
I'm curious. If it is not too much effort. Can anyone give me a good example of a code snippet, where switching to unicode increased readability?

**Comment by sloede** [comment]
It has been decided to obey the law of the witch-overlord aka Trixi, which is to only allow ASCII for code (Unicode may still be used in comments and documentation/docstrings where it helps readability).
